version: '3'

services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "80:80"
    restart: always

  hello:
    build:
      context: .
      dockerfile: Dockerfile.hello
    restart: always
