[package]
name = "kimiyuki"
version = "0.1.0"
authors = ["Kimiyuki Onaka <kimiyuki95@gmail.com>"]
edition = "2018"

[dependencies]
rust_game_base = {path = "../../infra/rust_game_base"}
itertools = "0.9.0"
