name: Secrets

on:
  push

jobs:
  check:
    name: Check
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Find API keys
        run: |
          if git grep ca3e30a5; then
            echo 'API key found!!!'
            exit 1
          fi
