name: Sentinel

on:
  push:
    branches:
      - no_such_branch

jobs:
  deploy:
    name: Deploy to sentinel
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Deploy via SSH
      run: |
        cd infra
        mkdir -p ~/.ssh
        gpg --quiet --batch --yes --decrypt --passphrase="${{ secrets.ENCRYPTION_KEY }}" --output ~/.ssh/id_ed25519 ssh_keys/deploy.gpg
        chmod 600 ~/.ssh/id_ed25519
        scripts/docker-compose.sh -H ssh://deploy@34.105.114.17 -f compose.sentinel.yaml -p sentinel up --build --detach --remove-orphans
