name: Sentinel

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy to sentinel
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Deploy via SSH
      run: |
        cd infra/sentinel
        mkdir -p ~/.ssh
        gpg --quiet --batch --yes --decrypt --passphrase="${{ secrets.ENCRYPTION_KEY }}" --output ~/.ssh/automation ssh_keys/automation.gpg
        chmod 600 ~/.ssh/automation
        ssh -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -i ~/.ssh/automation nya@34.105.114.17 bash <<EOF
        set -ex
        dir=\$(mktemp -d)
        trap "cd /; rm -rf \$dir" EXIT
        cd "\$dir"
        git clone git@github.com:nya3jp/icfpc2020.git .
        git checkout ${{ github.sha }}
        sudo infra/sentinel/update.sh
        EOF
