name: Submit

jobs:
  submit:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Fetch whole repository
        run: git fetch origin
      - name: Configure
        run: git config --local user.email "bot@example.com" && git config --local user.name "Bot"
      - name: Run make_submissions.sh
        run: ./infra/make_submissions.sh --push
