name: Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.44.1
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Run test.sh
        run: ./test.sh
